# Page settings

baseURL = "http://example.org/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Richard Didham"
        tagline = "Senior Software Engineer"
        avatar = "circle_headshot.png"


    [params.summary]
        enable = true
        text = "I am a full-stack developer with a strong interest in engineering applications."





    [params.contact]
        enable = true
        location = "Los Angeles"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "619 985 4799"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "rdidham@gmail.com"








    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Languages"
        [[params.skills.list.items]]
        details = "Python"
        [[params.skills.list.items]]
        details = "JavaScript"
        [[params.skills.list.items]]
        details = "Node.js/ASP.NET"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MSc in Computational Mechanics"
        university = "University of California, Berkeley"
        dates = "2018 - 2019"
        [[params.education.list]]
        degree = "BSc in Mechanical Engineering"
        university = "University of California, Berkeley"
        dates = "2014 - 2018"



    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"




    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Sailing"
        [[params.interests.list]]
        name = "Boat building"
        [[params.interests.list]]
        name = "Cycling"






    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Senior Full-Stack Developer"
        dates = "Sept 2022 - Present"
        company = "Boeing Research and Technology"
        details = "Led development of a multi-tenant, cloud-based platform and InnerSource code base which allows teams to rapidly deploy web apps to store engineering data."
        [[params.experience.list.items]]
        details = "**Core tech stack:** Django, PostgreSQL, S3 Storage, Boostrap, DataTables, Gitlab CI/CD, Docker, Openshift"
        [[params.experience.list.items]]
        details = "Design allows web apps and accompanying APIs to be generated dynamically from a simple definition of the needed data schema"
        [[params.experience.list.items]]
        details = "Currently 16 applications have been deployed serving teams across a variety of engineering disciplines (200+ users)"
        [[params.experience.list.items]]
        details = "Promoted strong documentation practices which enabled teams to develop and deploy apps without needing a single meeting"
        [[params.experience.list.items]]
        details = "Led a team of 3 developers: ran daily standups, managed task board, coordinated with customers"
        [[params.experience.list.items]]
        details = "Presented novel aspects of the project at BTEC 2024, Boeing’s annual internal conference on technology developed within the company (< 30% of abstract submissions are accepted)"



        [[params.experience.list]]
        title = "Full-Stack Developer"
        dates = "July 2021 – Sept 2022"
        company = "Boeing Research and Technology"
        details = "Contributed to a desktop C# application which automates repetitive test planning and engineering tasks."
        [[params.experience.list.items]]
        details = "**Core tech stack:** .Net Core, React, Material UI, Node.js, Gitlab CI/CD, VMware Tanzu, SQL Server"
        [[params.experience.list.items]]
        details = "Developed an admin web UI and accompanying REST backend for better access to the desktop app’s SQL database"
        [[params.experience.list.items]]
        details = "Built CI/CD pipelines to deploy both the admin UI and REST backend to Tanzu cloud platform"
        [[params.experience.list.items]]
        details = "Implemented major overhauls to reduce latency and eliminate race conditions in the desktop app"
        

        [[params.experience.list]]
        title = "Structures Research Engineer "
        dates = "July 2019 – July 2021"
        company = "Boeing Research and Technology"
        [[params.experience.list.items]]
        details = "Developed Python tools to process results from Finite Element Analysis (FEA) simulations"
        [[params.experience.list.items]]
        details = "Conducted various static and dynamic non-linear FEA simulations"
        [[params.experience.list.items]]
        details = "Developed a Python library which converted between FEA element strains and node displacements for a machine learning project using graph neural networks to predict structural vibration"




    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Sail Scan"
        meta = "Open Source"
        details = "Computer vision application which uses color based image thresholding to analyze sail shape on high performance sailboats."
        [[params.projects.list.items]]
        details = "**Core Tech Stack:** Core tech stack: OpenCV, Python multiprocessing, Tkinter, pytest"
        [[params.projects.list.items]]
        details = "Allows sailors to better characterize their setup and quantitatively assess changes to sail shape"
        [[params.projects.list.items]]
        details = "Beta version in use by professional sailors "
        [[params.projects.list.items]]
        details = "Optimized for performance, processing 7,000 5MB images in 30 minutes on a typical notebook"
        [[params.projects.list.items]]
        details = "MVP architecture with comprehensive test coverage"









    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/rdidham"
        title = "rdidham"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//www.linkedin.com/in/richard-didham-80660a13a/"
        title = "Richard Didham"






