# Page settings

baseURL = "https://rdidham.github.io/"
relativeURLs = true
uglyURLs = true
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"






[params]
    author = "CowboySmall"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"


    primaryColor = "#1e8449"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Richard Didham"
        tagline = "Senior Software Engineer"
        avatar = "circle_headshot.png"


    [params.summary]
        enable = true
        text = "I am an experienced full-stack developer with an academic background in numerical methods and mechanical engineering. I'm interested in leveraging my expertise in these areas to tackle complex, data-intensive problems in software development."




    [params.contact]
        enable = true
        location = "Los Angeles"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "619 985 4799"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "rdidham@gmail.com"








    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Languages and Frameworks"
        [[params.skills.list.items]]
        details = "Python, JavaScript, C#, Java, SQL"
        [[params.skills.list.items]]
        details = "Django, React, .Net Core, Boostrap, Material UI, DataTables"
        
        [[params.skills.list]]
        title = "DevOps"
        [[params.skills.list.items]]
        details = "Docker Containers, Kubernetes, Openshift"
        [[params.skills.list.items]]
        details = "Gitlab CI/CD, VMware Tanzu, Github Actions"

        [[params.skills.list]]
        title = "Web Security"
        [[params.skills.list.items]]
        details = "Token authentication"
        [[params.skills.list.items]]
        details = "Session authentication"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Full-stack development"
        [[params.skills.list.items]]
        details = "Technical leadership"
        [[params.skills.list.items]]
        details = "InnerSource maintenance"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "MSc in Computational Mechanics"
        university = "University of California, Berkeley"
        dates = "2018 - 2019"
        [[params.education.list]]
        degree = "BSc in Mechanical Engineering"
        university = "University of California, Berkeley"
        dates = "2014 - 2018"



    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"




    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Sailing"
        [[params.interests.list]]
        name = "Boat building"
        [[params.interests.list]]
        name = "Cycling"






    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Software Engineer L3"
        dates = "Sept 2022 - Present"
        company = "Boeing Research and Technology"
        details = "Led development of a multi-tenant, cloud-based platform and InnerSource code base which allows teams to rapidly build and deploy web apps to store engineering data."
        [[params.experience.list.items]]
        details = "**Core tech stack:** Django, PostgreSQL, S3 Storage, Boostrap, DataTables, Gitlab CI/CD, Docker, Openshift"
        [[params.experience.list.items]]
        details = "Fully functioning web apps and APIs are generated dynamically from a simple definition of the needed data schema"
        [[params.experience.list.items]]
        details = "Allows new teams can go from zero to a deployed production application in a matter of hours"
        [[params.experience.list.items]]
        details = "To date 16 applications have been deployed, serving 200+ users across a variety of engineering disciplines"
        [[params.experience.list.items]]
        details = "Promoted strong documentation practices which has allowed teams to develop and deploy apps without needing a single meeting with maintainers"
        [[params.experience.list.items]]
        details = "Led a team of 3 developers: ran daily standups, managed task board, coordinated with customers"
        [[params.experience.list.items]]
        details = "Presented novel aspects of the project at BTEC, an annual internal conference which highlights technology developed within Boeing (< 30% of submissions are accepted)"



        [[params.experience.list]]
        title = "Software Engineer L2"
        dates = "July 2021 – Sept 2022"
        company = "Boeing Research and Technology"
        details = "Built microservices to accompany a desktop C# application which automates repetitive test planning and engineering tasks."
        [[params.experience.list.items]]
        details = "**Core tech stack:** .Net Core, React, Material UI, Node.js, Gitlab CI/CD, VMware Tanzu, SQL Server"
        [[params.experience.list.items]]
        details = "Developed an admin web UI and accompanying REST backend for better access to the desktop app’s SQL database"
        [[params.experience.list.items]]
        details = "Implemented  CI/CD pipelines to deploy both the admin UI and REST backend to Tanzu cloud platform"

        

        [[params.experience.list]]
        title = "Structures Research Engineer L2"
        dates = "July 2019 – July 2021"
        company = "Boeing Research and Technology"
        [[params.experience.list.items]]
        details = "Developed Python tools to process results from Finite Element Analysis (FEA) simulations"
        [[params.experience.list.items]]
        details = "Conducted various static and dynamic non-linear FEA simulations"
        [[params.experience.list.items]]
        details = "Developed a Python library which converted between FEA element strains and node displacements for a machine learning project using graph neural networks to predict structural vibration"




    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Sail Scan"
        meta = "Repo access available upon request"
        details = "Computer vision application which uses color based image thresholding to analyze sail shape on high performance sailboats."
        [[params.projects.list.items]]
        details = "**Core Tech Stack:** Core tech stack: OpenCV, Python multiprocessing, Tkinter, pytest"
        [[params.projects.list.items]]
        details = "Allows sailors to better characterize their setup and quantitatively assess changes to sail shape"
        [[params.projects.list.items]]
        details = "Beta version in use by professional sailors "
        [[params.projects.list.items]]
        details = "Optimized for performance: processes 7,000 5MB images in 30 minutes on a typical notebook"
        [[params.projects.list.items]]
        details = "MVP architecture with comprehensive test coverage"









    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/rdidham"
        title = "rdidham"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//www.linkedin.com/in/richard-didham-80660a13a/"
        title = "Richard Didham"






